# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: blog-api
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '%RUZhP1Zwc5&'
      MYSQL_DATABASE: db-blog
      
